### ISSUE TITLE
CM4 needs to be powered by the server

### ISSUE THREAD

**Issue by hobbit23** [raspberrypi/cmprovision#21]
Hi,

I connected two CM4s to the server via USB and ETH using a switch. This is working. Adding two more CM4 via ETH to the switch and power the board through another power supply which is not the server, the modules does not come up. I can see this because the ETH connection does not give any light and also the CMs are not listed in the webfrontend.

Can anyone acknowledge this way of powering the modules: I have to power through the server because of a communication (rpiboot).

regards

**Comment by maxnet** [comment]
If using Waveshare boards make sure the boot switch is set to "off". ETH connection light will NOT go on, if it is set to "on" and it will wait for rpiboot instead.

(ETH connection light will only function if something enables the Ethernet interface. Be it the bootloader or Linux kernel.)

>I connected two CM4s to the server via USB and ETH using a switch.

Would not power CM4s through the Pi either.
If using Waveshare boards use a powered USB hub.

(Note that the official Raspberry Pi CMIO boards do not take power from the micro USB connector, but require separate power through the barell connector.
So any power problems you may have are typically specific to Waveshare)

**Comment by hobbit23** [comment]
I am using the carrier board from https://sourcekit.cc/#/ and not waveshare.
The boot switch is on "OFF". Otherwise I can not access to the eMMC. Power only via ETH is also not possible with "fresh" boards unfortunately.
When I connect the already flashed CM4s to an external USB power supply then the devices to not boot up. I used a standard 230AC to 5VDC connector.

**Comment by maxnet** [comment]
>I am using the carrier board from https://sourcekit.cc/#/ and not waveshare.

Oh, I think that has the switch the other way around than is the case on Waveshare boards.

>The boot switch is on "OFF". Otherwise I can not access to the eMMC.

You mean you cannot access eMMC with rpiboot?
In that case, do set it to "ON" if the modules are NOT flashed and you want to perform a network boot.


>When I connect the already flashed CM4s to an external USB power supply then the devices to not boot up.

Cannot use network boot with already flashed units.
May need to use powered USB hub, like this (untested, do not have the board you have): https://www.amazon.de/-/nl/dp/B076YRSWH3/ref=sr_1_3?crid=2S66YJD2GZVG2

**Comment by hobbit23** [comment]
I dont know anything about the waveshare products

I can access eMMC with my windows laptop using rpiboot tool to set the CM4 into the booting stage. This is what the server will do as well but on my sight, the server only can connect to the eMMC of the connected CM4 when connected directly to the server. You mentioned it differently

With already flashed units I can access to the server and it is working then. Only when connected more than one device the server starts new and can not handle lets say 4 CM4 modules at the same time which I did expected

**Comment by maxnet** [comment]
>With already flashed units I can access to the server and it is working then. Only when connected more than one 
>device the server starts new and can not handle lets say 4 CM4 modules at the same time which I did expected

My educated guess is that if you do "dmesg" on the Pi 4, you are going to see "over-current change" messages.

A Pi 4 can only apply 1.2 ampere through its USB ports in total.
Need more, get a powered USB hub,

**Comment by hobbit23** [comment]
with dmesg I can see


[  +0.205596] usb 1-1.4: device not accepting address 44, error -71
[  +0.000523] usb 1-1-port4: unable to enumerate USB device

**Comment by hobbit23** [comment]
still the two connected CM4  boards are visible in the server but the start and stop the flashing all the time

**Comment by hobbit23** [comment]
-	I can not flash multiple CM4 at one time. It is starting and stopping again and again
-	The devices are visible in the CM list
-	I do need a USB connection because already flashed CM4s can not only be connected via ETH

**Comment by hobbit23** [comment]
Hi, your colleagues mentioned that there is a small programm needed to be handeled by the CMprovisioning server. If your script is writing zeros, even there is no small programm. Will this be flashed then by the server? Do I have to enable the booting from eMMC via the boot-switch like before? When using fresh CM4s from the factory I do not have to do this?

**Comment by maxnet** [comment]
>Hi, your colleagues mentioned that there is a small programm needed to be handeled by the CMprovisioning server. If 
>your script is writing zeros, even there is no small programm. Will this be flashed then by the server?

The small Linux utility operating system that is used by cmprovision during provisioing (the scriptexecute image) is network booted on demand.
When you network boot an image, the image gets loaded to RAM, and is started from there.
So "flashed" is not the right word, as it is not in flash.

>Do I have to enable the booting from eMMC via the boot-switch like before?

You need to disable eMMC boot when using rpiboot to zero out the start of eMMC.
Enable it again, when network booting.

>When using fresh CM4s from the factory I do not have to do this?

No need to zero out eMMC that is already empty.

**Comment by hobbit23** [comment]
Can you please give me an instruction to run the script ? I dont have another Pi for running this so i have to use windows. Do you have any instructions for me? As far as I can see the scripts wants to be act on raspberry with device sda. How can I run the script and how I can be sure to have the device CM4 is connected?

best regards
Nils

**Comment by maxnet** [comment]
With all due respect, I think it may be better if you do NOT try to modify that script to run under Windows.
There is a slight risk that you wipe out the partition table of the wrong drive, if you get it wrong.


If it is just a small number of CM4 modules you want to wipe, another alternative is just starting "rpiboot" under Windows to have the CM4 present itself as a mass storage device.
Can then start Raspberry Imager under Widows, and choose "wipe disks / format as FAT32" as "operating system"
Devices wiped this way, should also network boot again...

**Comment by hobbit23** [comment]
thank you. that worked with the erasing of the CM4. But still (I have now 3 CM4s erased and connected via ETH to the ETH Switch with the cm-server) it is not possible to parallel flash

**Comment by hobbit23** [comment]
only one of three devices is listed

**Comment by maxnet** [comment]
>thank you. that worked with the erasing of the CM4. But still (I have now 3 CM4s erased and connected via ETH to the 
>ETH Switch with the cm-server) it is not possible to parallel flash

Suggest you score some official Raspberry Pi CMIO boards, to rule out there is not anything out-of-the-ordinary with your third-party boards.

**Comment by hobbit23** [comment]
can you provide me those? or do you have any reference link? I dont have any problem when using the balenaetcher tool for windows. 
Seems to be that the ETH booting is not working

**Comment by hobbit23** [comment]
I don't think it is the carrierboard. If it is not, how can we have a look inside the system? any idea from your side to get closer to the issue? I deleted the CM4 as you mentioned. Also via the raspi image and i tried with windows as well. It has to be FAT32 right?

**Comment by JamesH65** [comment]
Raspberry Pi does not sell the IO board directly, you will need to get one from a reseller.

**Comment by maxnet** [comment]
https://www.raspberrypi.com/products/compute-module-4-io-board/
https://www.berrybase.de/detail/index/sArticle/6822

They need to be powered by barell connector PSU.

**Comment by maxnet** [comment]
>I don't think it is the carrierboard. If it is not, how can we have a look inside the system? 

As mentioned before, the carrier boards should show debug output on HDMI in all cases.
But your mentioned previously yours do not.

The tiny Linux operating system we network boot writes what it is doing to display.
But also the bootloader in EEPROM that does the network booting itself writes stuff to display.
So even if network boot fails for whatever reason you should have visual on HDMI.

That kinda limits our debug options.
(Yes, there are other ways like serial debug cables. But before going that route, get boards that are known good first....)

**Comment by hobbit23** [comment]
I have used this one "Waveshare 19838 CM4-DUAL-ETH-BASE" and it is also not working

**Comment by ghollingworth** [comment]
From my reading of the Waveshare website, If you've got the boot switch turned to 'on' then that means 'boot from USB' 

You can also connect the BOOT signal to GND
Or if power from the USB-C port

Any of these will make the device not boot through Ethernet

https://www.waveshare.com/wiki/Write_Image_for_Compute_Module_Boards_eMMC_version

**Comment by maxnet** [comment]
>I have used this one "Waveshare 19838 CM4-DUAL-ETH-BASE" and it is also not working

Note that on Waveshare boards the boot switch works the opposite way than other brands.



I do happen to have one of those dual-eth boards laying around.

Those should work if the network cable is in the port labeled "ETH0", the boot switch is set to OFF, and you allow it 40 seconds to boot.
Like this:

![20230516_163009](https://github.com/raspberrypi/cmprovision/assets/1123701/e9860a36-5dbb-47ec-bd51-4cd6c24d4730)

But it does is a board without HDMI, as well.
So if something is wrong things do are hard to debug as well.

**Comment by ghollingworth** [comment]
Looking at the schematics, the Waveshare board cannot be powered from the USB-C connector otherwise it will automatically go straight to USB boot and won't boot through Ethernet.

**Comment by maxnet** [comment]
>Looking at the schematics, the Waveshare board cannot be powered from the USB-C connector otherwise it will automatically go straight to USB boot and won't boot through Ethernet.

Does network boot for me...

**Comment by ghollingworth** [comment]
That's because what you have is not:

https://www.waveshare.com/wiki/CM4-DUAL-ETH-BASE

I'm unsure what it is that you have!  I can't find it on their website!

But for things that have both a DC jack and a USB-C you _must_ power it through DC jack, if it's only got USB-C then it doesn't matter

**Comment by ghollingworth** [comment]
You have the mini version

https://www.waveshare.com/wiki/CM4-DUAL-ETH-MINI

**Comment by maxnet** [comment]
>But for things that have both a DC jack and a USB-C you must power it through DC jack, if it's only got USB-C then it 
>doesn't matter

You are right that I have a different dual-eth one.

I do happen to have a single Ethernet Waveshare one with both DC jack and USB-C, and that one does work no matter how you power it.
In both cases it does go through BCM-USB (5) first, but will timeout and go to network boot eventually if you have enough patience:

![waveshare](https://github.com/raspberrypi/cmprovision/assets/1123701/bd45acd1-95c0-4a37-a142-27fbbf3a3d40)
