### ISSUE TITLE
NVMe Support

### ISSUE THREAD

**Issue by Panxatony** [raspberrypi/cmprovision#29]
If I recognize correctly, the network boot image does not support NVMe. There is currently an exciting project https://computeblade.com/ and support for NVMe alongside eMMC would be very helpful.

**Comment by timg236** [comment]
Off topic; the CM4 rpiboot mass storage gadget supports NVMe. Slightly more manual process though.

**Comment by maxnet** [comment]
>If I recognize correctly, the network boot image does not support NVMe. 

Yes, cmprovision is older than the Pi had NVMe support.

Should work if you toss CONFIG_BLK_DEV_NVME=y in https://github.com/raspberrypi/scriptexecutor/blob/master/scriptexecute/board/kernelconfig-cm4.armv7 and recompile the Linux kernel.
(Or steal the kernel from Imager embedded and toss it in /var/lib/cmprovision/scriptexecute ).

**Comment by Panxatony** [comment]
> > If I recognize correctly, the network boot image does not support NVMe.
> 
> Yes, cmprovision is older than the Pi had NVMe support.
> 
> Should work if you toss CONFIG_BLK_DEV_NVME=y in https://github.com/raspberrypi/scriptexecutor/blob/master/scriptexecute/board/kernelconfig-cm4.armv7 and recompile the Linux kernel. (Or steal the kernel from Imager embedded and toss it in /var/lib/cmprovision/scriptexecute ).

That was the hint I was missing. Thank you very much, it worked.

**Comment by Panxatony** [comment]
That was the hint I was missing. Thank you very much, it worked.
