### ISSUE TITLE
Provision CM4 over USB only?

### ISSUE THREAD

**Issue by jolla** [raspberrypi/cmprovision#33]
Is it possible to provision the CM4 over USB only rather than ethernet? The carrier board we are using in a project does not have an ethernet port but we'd still like to use the cmprovision to provision the CM4s, similarly to how the CM3's are provisioned?

**Comment by maxnet** [comment]
Should work provided you toss in /var/lib/cmprovision/scriptexecute/config.txt under the [cm4] section:

```
dtoverlay=dwc2,dr_mode=peripheral
cmdline=cmdline.txt.ipv6ll
```

And your server system is configured to use predictable IPV6 link-local addresses.
cmprovision does currently configure dhcpcd to that extend automatically (puts "slaac hwaddr" in /etc/dhcpcd.conf), but if you use something else like networkmanager its settings may need to be adjusted manually.

**Comment by jolla** [comment]
Working great, thank you!
