### ISSUE TITLE
Backup SD Card images of cmprovision Raspbian OS requires creating the nginx log folder for nginx to start

### ISSUE THREAD

**Issue by ES-Ian** [raspberrypi/cmprovision#35]
After creating a 1:1 image of the cmprovisoning Pi SD Card using the builtin Raspbian disk imager software tool, running the newly created SD Card results in its nginx instance failing to start due to /var/log/nginx folder missing from /var/log directory. 

Creating this folder manually and restarting the nginx service will result in the cmprovison web ui running successfully.

Original SD Card from which the copy is made is not affected.

**Comment by maxnet** [comment]
That sounds more like a failure in making the image, than a cmprovision problem.
Please be very specific how you made the image.

Raspberry Pi Imager can only write already made .img files.
It does not make those .img files...
Other tools (e.g. the SD card copier thing) do NOT make 1:1 copies, but shuffle individual files around.
