### ISSUE TITLE
provisioner on bookworm

### ISSUE THREAD

**Issue by knachte** [raspberrypi/cmprovision#49]
I've set up a provisioner on a bookworm install and am seeing problems with the network settings, both in the manual which is no longer up to date and after installing the provisioner, with files like /etc/dhcpcd.conf no longer being he correct ones to use. 

Are there plans to upgrade the provisioner/documentation to work with bookworm?

**Comment by synaption** [comment]
what are you using instead of /etc/dhcpcd.conf?

**Comment by knachte** [comment]
It seems they switched to nmcli: https://raspberrypi.stackexchange.com/questions/144886/how-to-set-up-a-static-ip-on-raspberry-pi-5-with-raspbian-dhcpcd-conf-missing.

**Comment by synaption** [comment]
I did it with /etc/systemd/network/eth0.network
```
[Match]
Name=eth0

[Network]
Address=172.20.0.1/16
```

**Comment by synaption** [comment]
I did this:
sudo nano /etc/network/interfaces.d/eth0
```
auto eth0
iface eth0 inet static
    address 172.20.0.1
    netmask 255.255.0.0
```

**Comment by grevelle** [comment]
You can also configure through the CLI. This survives reboots.

`sudo nmcli con add type ethernet con-name eth0-static ifname eth0 ip4 172.20.0.1/16`

**Comment by magicsmoke** [comment]
Well I just wasted half a day on this. Suspecting originally a hardware issue.

Updated documentation would be have been very appreciated.
