### ISSUE TITLE
Support for CM1?

### ISSUE THREAD

**Issue by lurch** [raspberrypi/cmprovision#8]
(Not a feature I'm need, I'm just asking out of curiosity...)

IIRC the same `usbboot` works with both CM1 and CM3, so is there any specific reason why this `cmprovision` repo won't/can't also work for CM1? And if it _does_ already work with CM1, it might be useful to mention that in the README.

**Comment by maxnet** [comment]
Do not ship a ARMv6 kernel.

**Comment by lurch** [comment]
Ahhh, fair enough.
